services:
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "${RABBITMQ_PORT_AMQP}:5672"
      - "${RABBITMQ_PORT_UI}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      args:
        CMD: server
    ports:
      - "8080:8080"
    environment:
      LISTEN_ADDR: ":8080"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}?sslmode=disable"
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  client:
    build:
      context: .
      args:
        CMD: client
    ports:
      - "8081:8081"
    environment:
      SERVER_ADDR: "server:8080"
      WEB_ADDR: ":8081"
    depends_on:
      - server

volumes:
  rabbitmq_data:
  postgres_data:
